### ISSUE TITLE
Bauxite Dust = orDictonary.dustIridium?

### ISSUE THREAD

**Issue by cyberpunkbln** [MCJediYoda/HardcoreORE#10]
Hello,

is this correct so, i think dustAluminium where correct, or?

thx

**Comment by MCJediYoda** [comment]
yes.  it should be aluminum.

**Comment by cyberpunkbln** [comment]
Hmm can it be that another mod overwrite your OreDictonary.Entry? f3+h says Bauxite Dust are in the Ore Dictonary as dustIridium.

**Comment by MCJediYoda** [comment]
I will have it fixed tonight.  It probably was just a copy paste error on my part.

**Comment by cyberpunkbln** [comment]
cool thx
