### ISSUE TITLE
[Licensing] Soartex Textures

### ISSUE THREAD

**Issue by artdude543** [MCJediYoda/HardcoreORE#11]
Hello,

I am the current owner of Soartex Fanver and have been pointed to the direction of this mod due to the unauthorized textures you are hosting on here and with the mod.

I can see that you have created textures for your mod for Soartex Fanver; however hosting them on your repo is against our [license](https://soartex.net/license#fanver).

The following files are affected:
- https://github.com/MCJediYoda/HardcoreORE/blob/master/HardcoreORE-Soartex-1.10.2.zip
- https://github.com/MCJediYoda/HardcoreORE/blob/master/HardcoreORE-Soartex-1.11.2.zip

If you'd like to add support officially for your mod then please submit a PR to @Soartex-Modded to the relevant repo version. You'd also need to follow this [guide](http://wiki.soartex.net/modded/02-04-2015/making-a-modpack-json/). To create the correct patch for our automated systems for building/creating downloads.

Once completed our server does the rest and your download will be on our CDN's which you can link where ever you'd wish.

But in terms of the files hosted here can then please be removed.

If you have any questions about this you can comment or if you want it done privately please use the email on my profile.

Thanks,
Kieron

**Comment by MCJediYoda** [comment]
Sure.  I will submit a PR to have the textures for my mod added to @Soartex-Modded.  I removed the two files listed above. 
Thank you
