### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by GeebsRilie** [MCJediYoda/HardcoreORE#3]
Just wondering if this has been an issue or if it just conflicting with other mods?

**Comment by MCJediYoda** [comment]
I'll take a closer look.  Are you using 1.11.2?

**Comment by GeebsRilie** [comment]
Yes.

**Comment by MCJediYoda** [comment]
I fixed it.  The salt ore generation overlapped chunks.  I tweaked this a bit and tested.  I generated several worlds 2 which happen to spawn me on islands in the ocean.  No lag reported and Journeymap looked good.  Please let me know if you encounter any further issues.  Thanks

**Comment by GeebsRilie** [comment]
Thank you!

The foregoing may include confidential and/or privileged information.  If
you are not the intended recipient, do not read, distribute, reproduce or
otherwise disclose this transmission or any of its contents.  If delivered
in error, please forward the email back to sender, delete from your
computer and disregard information contained therein.  Thank you.
