### ISSUE TITLE
1.11.2 Feature request.

### ISSUE THREAD

**Issue by MrSapient** [MCJediYoda/HardcoreORE#4]
Is there anyway you would be willing to add in a system that works like the mod OreSpawn since you already give all the ores in one mod i would like to be able to disabled all the same ores in every other mod out with this one mod. The reason i'm requesting you to add this system is because i  dont believe the mod OreSpawn is actively being developed and there is currently no mod in 1.11.2 that offers this system i'm requesting.

https://github.com/MinecraftModDevelopmentMods/OreSpawn

**Comment by MCJediYoda** [comment]
I am familiar with Orespawn and use it in all my modpacks.  I will see what I can make of the Orespawn code and see if I can incorporate something.  I did build the Orespawn 1.11 code and have been using it in my dev modpack. I'll see if I can look more into the code.  I'd be happy to work with you and get what you need for your modpack.  I'm currenty working on an update which should be read tonight.  After that I can work more on the oregen stuff.   Thanks

**Comment by MrSapient** [comment]
Thanks for the willingness to try.. I dont need any special help with my pack just a way to control ore in all the mods and have it spawn with just one mod.

**Comment by MCJediYoda** [comment]
Most mods that I have come across allow you to disable their oregen for their mod in their configs.

**Comment by MrSapient** [comment]
Most do but they still registered the ore and it still shows up in JEI and what not .. I want to be able to completely remove them.

**Comment by MrSapient** [comment]
Any luck sir?

**Comment by MCJediYoda** [comment]
No.  I was thinking and have you checked into unidict?  I use this mod to unify all my ores in my modpacks.  It may be something you can use.

**Comment by MrSapient** [comment]
I have looked at that mod.. Im just not sure it can do everything i want... like control ore spawns.

**Comment by MCJediYoda** [comment]
OreSpawn for 1.11.2 has been released
https://minecraft.curseforge.com/projects/mmd-orespawn/files/2442963
