### ISSUE TITLE
Crash with 1.11.2-0.0.21

### ISSUE THREAD

**Issue by InkDragon** [MCJediYoda/HardcoreORE#5]
https://pastebin.com/xat51Lm9
Seems to have something to do with tinker's fluid model

Runs fine with version 1.11.2-0.0.20

**Comment by IchigoGames** [comment]
yap i also crashed after updating https://pastebin.com/T44tpT93

**Comment by MCJediYoda** [comment]
I'll take a look and have a fix tonight.  Thanks

**Comment by MCJediYoda** [comment]
I updated 1.11.2 21a for the crash.  It was crashing on the Invar fluid so I added a check for Nickel Ore.  Can you let me know if 21a fixed it?

**Comment by InkDragon** [comment]
Seems to have fixed it(did not explode when loaded)! Thank you

**Comment by MCJediYoda** [comment]
Thanks for the feedback
