### ISSUE TITLE
Ore Shrubs Support

### ISSUE THREAD

**Issue by InkDragon** [MCJediYoda/HardcoreORE#6]
It was suggested by the author of [Ore Shrubs](https://minecraft.curseforge.com/projects/ore-shrubs) to request some interplay between the two mods since Ore Shrubs doesnt pick up your ores for some reason

**Comment by MCJediYoda** [comment]
Hey InkDragon,  I will look into this.  That's a good idea.  It will be nice to have the two mods work together.  I will see what is all involved this weekend.  Thanks

**Comment by InkDragon** [comment]
Thank you! I think it might be as simple as having Hardcore Ore generate a few json files in Ore Shrubs config directory. I'm not 100% on that but since ore shrubs offers the option to create custom shrubs it is a possibility.

**Comment by MCJediYoda** [comment]
I'll fix it tonight.  Thanks

**Comment by Lhykos** [comment]
@MCJediYoda If there is something I should change in my mod for any compatibility, let me know it! Would be nice if our mods work together!

**Comment by MCJediYoda** [comment]
I seen this json file.  
https://github.com/Lhykos/OreShrubs/blob/master/custom-shrubs-example/mymodid.json

 I would like to do something like this without actually generating the json file and just send the information directly to oreshrubs.  Is there an API i can use or source code available for ore shrubs?
Thanks.

**Comment by Lhykos** [comment]
I'm not finished with the API yet, but I let you know when it's done! But I have found the solution for the problem. My mod now should know the materials from HardcoreORE. (The ones I support.) I will update my mod!

**Comment by MCJediYoda** [comment]
ok thanks.  Once you have the API completed I will add support for Ore Shrubs.  Looking forward to it.

**Comment by Lhykos** [comment]
I finished the API. You can get them here: [OreShrubs-API](https://github.com/Lhykos/OreShrubs)

**Comment by MCJediYoda** [comment]
Thanks.  I'll check it out.
