### ISSUE TITLE
exception from Hardcore ORE Crash

### ISSUE THREAD

**Issue by IchigoGames** [MCJediYoda/HardcoreORE#7]
Sorry but now i get a new crash from updating Hardcore in my Modpack

HardcoreORE-1.11.2-0.0.21a
Forge 2312
https://pastebin.com/kq3v3hya

**Comment by MCJediYoda** [comment]
I am looking into it.  Thanks

**Comment by MCJediYoda** [comment]
fixed in version 1.11.2-023
Thanks
