### ISSUE TITLE
Crash with HardcoreORE

### ISSUE THREAD

**Issue by IchigoGames** [MCJediYoda/HardcoreORE#8]
HardcoreORE-1.11.2-0.0.24
Minecraft 1.11.2
Crash report https://pastebin.com/a1xKbZP9
looks like a issure with hardcoreORE and tinkers

**Comment by IchigoGames** [comment]
https://pastebin.com/NrXKRgiB
HardcoreORE-1.11.2-0.0.25

**Comment by MCJediYoda** [comment]
let me know if 26a fixes it.  thanks

**Comment by IchigoGames** [comment]
it does thanks.
