### ISSUE TITLE
Titanium

### ISSUE THREAD

**Issue by boosterdev** [MCJediYoda/HardcoreORE#9]
Disabling titanium in the config, disables the entire mod
temporary solution: I:"Titanium Chances"=0

**Comment by MCJediYoda** [comment]
Which version of Minecraft 1.10. 1.11, or 1.12?

**Comment by boosterdev** [comment]
1.11.2

**Comment by MCJediYoda** [comment]
Thanks.  I will check it tonight and get a fix out right away.

**Comment by MCJediYoda** [comment]
should be fixed.
